### ISSUE TITLE
what does the parameter 'c' mean in 2d-KS?

### ISSUE THREAD

**Issue by qu-jiagang** [souvikghosh55/2-D-Periodic-Kuramoto-Sivashinsky-Equation#1]
2-D_periodic_Kuramoto_Sivashinsky_equation/ks2D.py
Line 155
`c = 100.`

**Comment by souvikghosh55** [comment]
Hi @Yanxiong666, Sorry for the late reply. The constant c is added to both the linear and non-linear, in order to ensure that the linear matrix A is positive definite. It is used for stabilization and it appears in the linear and non-linear terms on both sides of the original equation and eventually, the effect is cancelled out.
